exp_name: cmflow_cvpr
model: cmflow

## training 
num_points: 256
batch_size: 16 #16 32
val_batch_size: 8 #8 16
epochs: 60 #30
lr: 0.001 #0.001
decay_epochs: 1
decay_rate: 0.9

## device
cuda_device: '0'
no_cuda: False
seed: 1234
num_workers: 8

## dataset
eval: True
eval_split: test
dataset: vodDataset # vodClipDataset
train_set: train 
dataset_path: /mnt/12T/fangqiang/preprocess_res/flow_smp/
vis: False
save_res: False

## RaFlow method parameter
rigid_thres: 0.15

## CMFlow method parameter
vr_thres: 0.3 # 0.3 used for train
stat_thres: 0.5 # for test

## GRU parameter
mini_clip_len: 5
update_len: 5

## checkpoint
load_checkpoint: False
model_path: ''

